services:
  flutter-dev:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: flutter_docker
    user: root
    privileged: true
    volumes:
      - .:/app
      # Map local USB bus to the container
      - /dev/bus/usb:/dev/bus/usb
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
    stdin_open: true
    tty: true
